apiVersion: skaffold/v3
kind: Config
build:
  artifacts:
  - image: localdir1
    context: ./test/localdir1
    custom:
      buildCommand: ../../dist/contain-test
  - image: localdir-app
    context: ./test/localdir-app
    custom:
      buildCommand: ../../dist/contain-test -b docker.io/library/busybox
  - image: contextdir-app
    context: ./test
    custom:
      buildCommand: ../../dist/contain-test -b docker.io/library/busybox ./localdir-app
  - image: contextdir-config
    # todo should contain.yaml be found in CWD or in build context dir?
    context: test
    custom:
      buildCommand: ../../dist/contain-test -b docker.io/library/busybox localdir1

test:
- image: localdir1
  structureTests:
  - ./test/localdir1/test.yaml
- image: localdir-app
  structureTests:
  - ./test/localdir-app-test.yaml
