apiVersion: skaffold/v3
kind: Config
build:
  platforms:
  - linux/amd64
  - linux/arm64
  artifacts:
  - image: localdir1
    context: ./test/localdir1
    custom:
      buildCommand: contain -x
  - image: localdir-app
    context: ./test/localdir-app
    custom:
      buildCommand: contain -x -b docker.io/library/busybox
  - image: localdir-app-dot
    context: ./test/localdir-app
    custom:
      buildCommand: contain -x -b docker.io/library/busybox .
  - image: localdir-app-env
    context: ./test/localdir-app
    custom:
      buildCommand: CONTAIN_BASE=docker.io/library/busybox contain -x
  - image: contextdir-app
    context: ./test
    custom:
      buildCommand: contain -x -b docker.io/library/busybox ./localdir-app
  - image: contextdir-config
    context: test
    custom:
      buildCommand: contain -x localdir1
  - image: localdir-amd64
    context: ./test/localdir-app
    platforms:
    - linux/amd64
    custom:
      buildCommand: contain -x -b docker.io/library/busybox
  - image: localdir-arm64
    context: ./test/localdir-app
    platforms:
    - linux/arm64
    custom:
      buildCommand: contain -x -b docker.io/library/busybox
  - image: multilayer
    context: ./test/multilayer
    custom:
      buildCommand: contain -x
  - image: config-override
    context: ./test/localdir1
    custom:
      buildCommand: contain -x -b gcr.io/distroless/base-debian11:debug-nonroot
  - image: config-stdin
    context: ./test
    custom:
      buildCommand: |-
        cat <<EOF | IMAGE="" contain -x -c -
        base: gcr.io/distroless/base-debian11:debug-nonroot
        tag: $IMAGE
        layers:
        - localDir:
            path: localdir-app
            containerPath: /config-stdin
        EOF

test:
- image: localdir1
  structureTests:
  - ./test/localdir1/test.yaml
- image: localdir-app
  structureTests:
  - ./test/localdir-app-test.yaml
- image: localdir-app-dot
  structureTests:
  - ./test/localdir-app-test.yaml
- image: localdir-app-env
  structureTests:
  - ./test/localdir-app-test.yaml
- image: contextdir-app
  structureTests:
  - ./test/localdir-app-test.yaml
- image: contextdir-config
  structureTests:
  - ./test/localdir1/test.yaml
- image: multilayer
  structureTests:
  - ./test/multilayer/test.yaml
- image: config-override
  structureTests:
  - ./test/config-override-test.yaml
- image: config-stdin
  structureTests:
  - ./test/config-override-test.yaml
